"""Workspace bootstrap: scaffold ``.kanboard-plan.yml`` + state for a repo.

``init_workspace`` discovers ``docs/plan/*.md`` and writes a ready-to-sync
config that maps the repo to one Kanboard Project and each plan to a Swimlane
(``kanboard_project_strategy: workspace-project``), with a per-plan ``sync``
flag so stale plans can be opted out. Existing configs are not clobbered unless
``force=True``.
"""

from __future__ import annotations

from pathlib import Path

from .config import CONFIG_FILENAME, DEFAULT_LOCAL_DB_PATH, find_config
from .state import STATE_DIRNAME, STATE_FILENAME, state_path

DEFAULT_GLOBS = ["docs/plan/*.md"]


def discover_plans(workspace_root: str, globs: list[str] | None = None) -> list[str]:
    root = Path(workspace_root)
    globs = globs or DEFAULT_GLOBS
    found: set[str] = set()
    for pattern in globs:
        for match in root.glob(pattern):
            if match.is_file():
                found.add(str(match.relative_to(root)))
    return sorted(found)


def render_config(workspace_name: str, plan_rel_paths: list[str]) -> str:
    lines = [
        "# kanboard-plan-sync workspace configuration (generated by init-workspace).",
        "# The API token is NEVER stored here (env override, else local Kanboard DB).",
        "workspace:",
        f"  name: {workspace_name}",
        "",
        "kanboard:",
        "  url: http://127.0.0.1:8080/jsonrpc.php",
        "  username: jsonrpc",
        "  token_env: KANBOARD_API_TOKEN",
        f"  local_db_path: {DEFAULT_LOCAL_DB_PATH}",
        "  board_members:",
        "    - admin",
        "",
        "plans:",
    ]
    if plan_rel_paths:
        for rel in plan_rel_paths:
            lines.append(f"  - path: {rel}")
            lines.append("    plan_type: short-term")
            lines.append("    kanboard_project_strategy: workspace-project")
            lines.append("    sync: true")
    else:
        lines.append("  []")
    lines += [
        "",
        "plan_discovery:",
        "  glob:",
        "    - docs/plan/*.md",
        "",
    ]
    return "\n".join(lines)


def init_workspace(workspace_root: str, force: bool = False) -> dict:
    root = Path(workspace_root)
    if not root.is_dir():
        return {"status": "error", "error": "workspace directory does not exist", "workspace_root": str(root)}

    discovered = discover_plans(str(root))
    cfg_path = find_config(str(root))
    sp = state_path(str(root))

    # Always make sure an empty state file exists (idempotent).
    state_created = False
    if not sp.is_file():
        sp.parent.mkdir(parents=True, exist_ok=True)
        sp.write_text('{\n  "version": 1,\n  "references": {}\n}\n', encoding="utf-8")
        state_created = True

    if cfg_path is not None and not force:
        return {
            "status": "exists",
            "workspace_root": str(root),
            "config_path": str(cfg_path),
            "discovered_plans": discovered,
            "config_written": False,
            "state_created": state_created,
            "note": "config already present; re-run with force=True to regenerate",
        }

    target = root / CONFIG_FILENAME
    target.write_text(render_config(root.name, discovered), encoding="utf-8")
    return {
        "status": "forced" if cfg_path is not None else "created",
        "workspace_root": str(root),
        "config_path": str(target),
        "discovered_plans": discovered,
        "plan_count": len(discovered),
        "config_written": True,
        "state_created": state_created,
        "state_path": str(sp),
    }
